version: 1.0.'{build}'

configuration: Release

environment:
  matrix:
  - nodejs_version: "12"

platform:
  - x64

install:
  - ps: |
      try {
      Install-Product node $env:nodejs_version $env:platform
      } catch {
      echo "Unable to install node $env:nodejs_version, trying update..."
      Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
      }

build_script:
  - cmd: call build.bat

artifacts:
  - path: dist/lit-html-1.2.1.js
    name: lit-html esm
  - path: dist/lit-html-1.2.1.iife.js
    name: lit-html iife
  - path: dist/lit-element-2.3.1.js
    name: lit-html esm
  - path: dist/lit-element-2.3.1.iife.js
    name: lit-html iife
