name: lit-element

on: [push]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: build.sh
      shell: cmd

    - name: Archive lit-element
      uses: actions/upload-artifact@v1
      with:
        name: lit-element
        path: dist
