name: lit-element

on: [push]

jobs:
  build-lit:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: install node
      run: sudo apt install nodejs

    - name: install npm
      run: sudo apt install npm

    - name: Build
      run: ./build.sh

    - name: Archive lit-element
      uses: actions/upload-artifact@v1
      with:
        name: lit-element
        path: dist
